config {
  type: "table",

  database: "project-5bf2da38-3af5-48e5-860",
  schema: "epsilon_analytics",
  name: "fct_orders_daily",

  description: "Daily aggregated orders table",

  tags: ["finance", "daily_refresh"],

  partitionBy: "DATE(created_at)",

  clusterBy: [
    "status",
    "merchant_id"
  ]
}

WITH orders AS (

  SELECT
    order_id,
    user_id,
    merchant_id,
    order_value,
    created_at,
    status,
    delivery_time_minutes,
    DATE(created_at) AS order_date

  FROM `project-5bf2da38-3af5-48e5-860.epsilon_analytics.orders`

  WHERE status = 'delivered'

),

aggregated AS (

  SELECT
    *

  FROM orders

)

SELECT *
FROM aggregated